### ISSUE TITLE
Release 0.15.0 checklist

### ISSUE THREAD

**Issue by astrojuanlu** [poliastro/poliastro#1104]
## Preparing the release

* [x] Rerun all notebooks (pay special attention to new features)
* [x] Review documentation, optionally improving the user guide or adding new notebooks showcasing new functionality
* [x] Write the changelog and list of contributors
  - Commits since last release branch https://github.com/poliastro/poliastro/compare/0.14.0...master
  - Issues closed in this milestone https://github.com/poliastro/poliastro/milestone/16?closed=1 (note that there might be issues without milestone!)
  - Pull requests merged since last branching https://github.com/poliastro/poliastro/pulls?q=is%3Apr+is%3Amerged+merged%3A%3E%3D2020-05-02+sort%3Aupdated-asc

## Before the beta release

* [x] New branch
* [x] Bump version **to 0.15b1** in:
  - `README.md`
  - `__init__.py`
  - Sphinx `conf.py`
* [x] Check that the release branch will be tested on CI
* [x] Check all the badges in `README` point to the appropriate git **branch** (replace `master` by new branch `sed -i 's/master/.../g' README.md`)
* [x] Check that docs badges and URLs point to appropriate **tag** (replace `latest` by new tag, without sed!)
* [x] Commit
* [x] Generate sdist and bdist_wheel with `flit build`
* [x] `twine upload dist/* --repository-url https://test.pypi.org/legacy/`
* [x] Tag
* [x] Bump master to next development version

## Beta release

* [x] Push branch to GitHub **and tags**
* [x] Check on Test PyPI that the badges will work
* [x] Upload sdist and bdist_wheel to PyPI - *this step cannot be undone if the release is removed!* `twine upload dist/* --repository-url https://upload.pypi.org/legacy/`
* [x] Check Read the Docs

## Before final release

* [x] Backport any bugs
* [x] Update release date in changelog
* [x] Bump version **to 0.15.0** in:
  - `README.md`
  - `__init__.py`
  - Sphinx `conf.py`
* [x] Check that docs badges and URLs point to appropriate **tag** (replace `v0.15b1` by `v0.15.0`)
* [x] Commit
* [x] Generate sdist and bdist_wheel
* [x] `twine upload dist/* --repository-url https://test.pypi.org/legacy/`
* [x] Tag

## Final release

* [x] Push tag to GitHub
* [x] Upload sdist and bdist_wheel to PyPI - *this step cannot be undone if the release is removed!* `twine upload dist/* --repository-url https://upload.pypi.org/legacy/`
* [x] Check Read the Docs
* [x] Create GitHub release
* [x] Add Zenodo badge to GitHub release
* [x] Send announcement email with subject "ANN: poliastro 0.15.0 released 🚀"
* [x] Cherry pick release date to master
* [ ] Close milestone

**Comment by astrojuanlu** [comment]
Will complete the release notes _after_ the branching to avoid delaying the release any further.

**Comment by astrojuanlu** [comment]
Beta is released!

**Comment by astrojuanlu** [comment]
Backport:

- #1212
- #1214 
- #1217 
- #1219

**Comment by astrojuanlu** [comment]
On second thought, no need to backport #1219, since nbsphinx has already released a new version pinning it and new installations won't be affected.

**Comment by astrojuanlu** [comment]
Released! Only announcements left.

**Comment by jorgepiloto** [comment]
I just saw this is still opened. Is it related with a possible 0.15.1 version, @astrojuanlu?

**Comment by astrojuanlu** [comment]
Nop, it was related to the last missing bit: sending the email announcement :) Sorry it took me so much time, I'm now closing the milestone and the issue!

However, yes: releasing 0.15.1 might be interesting to avoid incompatibilities with astroquery.
