### ISSUE TITLE
Release 0.15.1 checklist

### ISSUE THREAD

**Issue by astrojuanlu** [poliastro/poliastro#1263]
## Before final release

* [x] Backport any bugs
* [x] Update release date in changelog
* [x] Bump version **to X.Y.Z** in:
  - `README.md`
  - `__init__.py`
  - Sphinx `conf.py`
* [x] Check that docs badges and URLs point to appropriate **tag** (replace `vX.Yb1` by `vX.Y.Z`)
* [x] Commit
* [ ] Generate sdist and bdist_wheel
* [ ] `twine upload dist/* --repository-url https://test.pypi.org/legacy/`
* [ ] Tag

## Final release

* [ ] Push tag to GitHub
* [ ] Upload sdist and bdist_wheel to PyPI - *this step cannot be undone if the release is removed!* `twine upload dist/* --repository-url https://upload.pypi.org/legacy/`
* [ ] Check Read the Docs
* [ ] Create GitHub release
* [ ] Add Zenodo badge to GitHub release
* [ ] Send announcement email with subject "ANN: poliastro X.Y.Z released 🚀"
* [ ] Cherry pick release date to master
* [ ] Close milestone

**Comment by astrojuanlu** [comment]
This ended up being 0.15.2 because I messed up the PyPI upload. Will send an announcement later on this week. Closing!
