### ISSUE TITLE
Release 0.16.0 checklist

### ISSUE THREAD

**Issue by astrojuanlu** [poliastro/poliastro#1347]
## Preparing the release

* [x] Rerun all notebooks (pay special attention to new features)
* [x] Review documentation, optionally improving the user guide or adding new notebooks showcasing new functionality
* [x] Write the changelog and list of contributors
  - Commits since last release branch https://github.com/poliastro/poliastro/compare/0.16.0...main
  - Issues closed in this milestone https://github.com/poliastro/poliastro/milestone/17?closed=1 (note that there might be issues without milestone!)
  - Pull requests merged since last branching https://github.com/poliastro/poliastro/pulls?q=is%3Apr+is%3Amerged+merged%3A%3E%3D2021-05-07+sort%3Aupdated-asc

## Before the beta release

* [x] New branch
* [x] Bump version **to X.Yb1** in:
  - `README.md`
  - `__init__.py`
* [x] Check all the badges in `README` point to the appropriate git **branch** (replace `main` by new branch `sed -i 's/main/.../g' README.md`)
* [x] Check that docs badges and URLs point to appropriate **tag** (replace `latest` by new tag, without sed!)
* [x] `git commit -m 'Bump to next beta version'`
* [x] Generate sdist and bdist_wheel with `python -m build`
* [x] `twine upload dist/* --repository-url https://test.pypi.org/legacy/`
* [x] Tag
* [x] Bump main to next development version

## Beta release

* [x] Push branch to GitHub **and tags**
* [x] Check on Test PyPI that the badges will work
* [x] Upload sdist and bdist_wheel to PyPI - *this step cannot be undone if the release is removed!* `twine upload dist/* --repository-url https://upload.pypi.org/legacy/`
* [x] Check Read the Docs

## Before final release

* [x] Backport any bugs
* [x] Update release date in changelog
* [x] Bump version **to X.Y.Z** in:
  - `README.md`
  - `__init__.py`
  - Sphinx `conf.py`
* [x] Check that docs badges and URLs point to appropriate **tag** (replace `vX.Yb1` by `vX.Y.Z`)
* [x] Commit
* [x] Generate sdist and bdist_wheel
* [x] `twine upload dist/* --repository-url https://test.pypi.org/legacy/`
* [x] Tag

## Final release

* [x] Push tag to GitHub
* [x] Upload sdist and bdist_wheel to PyPI - *this step cannot be undone if the release is removed!* `twine upload dist/* --repository-url https://upload.pypi.org/legacy/`
* [x] Check Read the Docs
* [x] Create GitHub release
* [ ] Add Zenodo badge to GitHub release
* [x] Send announcement email with subject "ANN: poliastro X.Y.Z released 🚀"
* [x] Cherry pick release date to main
* [x] Close milestone

**Comment by astrojuanlu** [comment]
Ideas while I was writing the changelog:

- Write down boilerplate template for changelogs
- Write down command to retrieve contributors list
- Should we have a distinct section for performance-only improvements?
- Should `poliastro.earth.sensors` be `poliastro.sensors`?
- Should we have a documention improvements section?

**Comment by astrojuanlu** [comment]
📣 poliastro 0.16b1 is out 📣

**Comment by astrojuanlu** [comment]
Backporting https://github.com/poliastro/poliastro/pull/1409/ to `0.16.x` ⚙️

**Comment by astrojuanlu** [comment]
Zenodo release does not appear ☹️ https://github.com/zenodo/zenodo/issues/2243

**Comment by astrojuanlu** [comment]
Milestone closed, so I'm already closing this issue and looking at the Zenodo issue at some other moment 🚀
