### ISSUE TITLE
Release 0.16.1 checklist

### ISSUE THREAD

**Issue by astrojuanlu** [poliastro/poliastro#1477]
## Preparing the release

* [x] Rerun all notebooks (pay special attention to new features)
* [x] Review documentation, optionally improving the user guide or adding new notebooks showcasing new functionality
* [x] Write the changelog and list of contributors
  - Commits since last release branch https://github.com/poliastro/poliastro/compare/0.16.0...main
  - Issues closed in this milestone https://github.com/poliastro/poliastro/milestone/17?closed=1 (note that there might be issues without milestone!)
  - Pull requests merged since last branching https://github.com/poliastro/poliastro/pulls?q=is%3Apr+is%3Amerged+merged%3A%3E%3D2021-12-08+sort%3Aupdated-asc
  - List of contributors: `git shortlog --summary --email ${BRANCHING_COMMIT}..`

Backport:

- https://github.com/poliastro/poliastro/pull/1426
- https://github.com/poliastro/poliastro/pull/1428
- https://github.com/poliastro/poliastro/pull/1432
- https://github.com/poliastro/poliastro/pull/1436
- https://github.com/poliastro/poliastro/pull/1441
- https://github.com/poliastro/poliastro/pull/1443
- https://github.com/poliastro/poliastro/pull/1444
- https://github.com/poliastro/poliastro/pull/1447
- https://github.com/poliastro/poliastro/pull/1449/
- https://github.com/poliastro/poliastro/pull/1453/
- https://github.com/poliastro/poliastro/pull/1455
- https://github.com/poliastro/poliastro/pull/1457
- https://github.com/poliastro/poliastro/pull/1458
- https://github.com/poliastro/poliastro/pull/1459
- https://github.com/poliastro/poliastro/pull/1462
- https://github.com/poliastro/poliastro/pull/1465
- https://github.com/poliastro/poliastro/pull/1466
- https://github.com/poliastro/poliastro/pull/1467
- https://github.com/poliastro/poliastro/pull/1476

## Before final release

* [x] Backport any bugs to release branch
* [x] Update release date in changelog of release branch
* [x] Bump version **to 0.16.1** in:
  - `README.md`
  - `__init__.py`
* [x] Check that docs badges and URLs point to appropriate **tag** (replace `v0.16.1b1` by `v0.16.1`)
* [x] Push commit to release branch and wait for CI to be green
* [x] Generate sdist and bdist_wheel running `python -m build`
* [x] `twine upload dist/* --repository-url https://test.pypi.org/legacy/`
* [x] Tag

## Final release

* [x] Push tag to GitHub
* [x] Upload sdist and bdist_wheel to PyPI - *this step cannot be undone if the release is removed!* `twine upload dist/*`
* [x] Check Read the Docs
* [x] Create GitHub release
* [x] Add Zenodo badge to GitHub release
* [x] Send announcement email with subject "ANN: poliastro 0.16.1 released 🚀"
* [x] Cherry pick release date to main
* [x] Close milestone

**Comment by astrojuanlu** [comment]
Everything ready but we need to wait until a fix for https://github.com/pypa/warehouse/issues/10720 is deployed.

**Comment by astrojuanlu** [comment]
Sending announcement right now 💪🏽 Ended up being 0.16.2 because of problems with RTD and the release notes.
