### ISSUE TITLE
Release 0.17.0 checklist

### ISSUE THREAD

**Issue by astrojuanlu** [poliastro/poliastro#1530]
## Preparing the release

* [x] Rerun all notebooks (pay special attention to new features)
* [x] Review documentation, optionally improving the user guide or adding new notebooks showcasing new functionality
* [x] Write the changelog and list of contributors
  - Commits since last release branch https://github.com/poliastro/poliastro/compare/0.16.3...main
  - Issues closed in this milestone https://github.com/poliastro/poliastro/milestone/18?closed=1 (note that there might be issues without milestone!)
  - Pull requests merged since last branching https://github.com/poliastro/poliastro/pulls?q=is%3Apr+is%3Amerged+merged%3A%3E%3D2021-11-21+sort%3Aupdated-asc
  - List of contributors: `git shortlog --summary --email $(git merge-base main 0.16.x)..`

## Before the beta release

* [x] New branch
* [x] Bump version **to X.Yb1** in:
  - `README.md`
  - `__init__.py`
* [x] Check all the badges in `README` point to the appropriate git **branch** (manually replace `main` by new branch)
* [x] Check that docs badges and URLs point to appropriate **tag** (manually replace `latest` by new tag)
* [x] `git commit -m 'Bump to next beta version'`
* [x] Generate sdist and bdist_wheel with `python -m build`
* [x] `twine upload dist/* --repository-url https://test.pypi.org/legacy/`
* [x] Tag
* [x] Bump main to next development version

## Beta release

* [x] Push branch to GitHub **and tags**
* [x] Check on Test PyPI that the badges will work
* [x] Upload sdist and bdist_wheel to PyPI - *this step cannot be undone if the release is removed!* `twine upload dist/*`
* [x] Check Read the Docs

## Before final release

* [x] Backport any bugs to release branch
* [x] Update release date in changelog of release branch
* [x] Bump version **to X.Y.Z** in:
  - `README.md`
  - `__init__.py`
* [x] Check that docs badges and URLs point to appropriate **tag** (replace `vX.Yb1` by `vX.Y.Z`)
* [x] Push commit to release branch and wait for CI to be green
* [x] Generate sdist and bdist_wheel running `python -m build`
* [x] `twine upload dist/* --repository-url https://test.pypi.org/legacy/`
* [x] Tag

## Final release

* [x] Push tag to GitHub
* [x] Upload sdist and bdist_wheel to PyPI - *this step cannot be undone if the release is removed!* `twine upload dist/*`
* [x] Check Read the Docs
* [x] Create GitHub release
* [x] Add Zenodo badge to GitHub release
* [x] Send announcement email with subject "ANN: poliastro X.Y.Z released 🚀"
* [x] Cherry pick release date to main
* [x] Close milestone

**Comment by astrojuanlu** [comment]
There will be no beta release this time.

![image](https://user-images.githubusercontent.com/316517/178151137-27acc914-97f3-4f9e-ac4b-a0c3a1201480.png)

**Comment by astrojuanlu** [comment]
The `v0.17.0` build on RTD keeps failing (#1535) but I did all the rest, so I'm closing.
