### ISSUE TITLE
Fix minor issues in Lambert

### ISSUE THREAD

**Issue by Juanlu001** [poliastro/poliastro#495]
_Follow-up from #492_

Several things to do:

* [x] Fix chord calculation, see https://github.com/poliastro/poliastro/issues/492#issuecomment-438808398
* [x] Improve error message when the vectors are parallel, see https://github.com/poliastro/poliastro/issues/492#issuecomment-439071294
* [ ] Remove misleading example from Lambert notebook `(_, v_l), (_, v_r) = izzo.lambert(k, r0, r, tof, M=1)` (do not remember what the intention was here), see https://space.stackexchange.com/questions/31967/multiple-revolution-lambert-problem/32020#comment97323_32020
* [ ] Clarify multi-revolution API (isn't the number of branches always 1 or 2? is it necessary to use a generator?), no need to wait for #114

**Comment by Juanlu001** [comment]
The first two have been addressed in #505.

**Comment by Juanlu001** [comment]
@jorgepiloto now that we understand the algorithm a bit better, perhaps we can keep the "low level Lambert API" in this notebook https://docs.poliastro.space/en/latest/examples/Revisiting%20Lamberts%20problem%20in%20Python.html#Multiple-revolutions but decide whether we still want to use a generator, or at least change the `(_, v_l), (_, v_r) = izzo.lambert(k, r0, r, tof, M=1)`?

**Comment by Juanlu001** [comment]
Done!
