### ISSUE TITLE
Release 0.13.0 checklist

### ISSUE THREAD

**Issue by Juanlu001** [poliastro/poliastro#734]
## Preparing the release

* [x] Rerun all notebooks (pay special attention to new features)
* [ ] Review documentation, optionally improving the user guide or adding new notebooks showcasing new functionality
* [x] Write the changelog and list of contributors
  - Commits since last release branch https://github.com/poliastro/poliastro/compare/v0.12.0...master
  - Issues closed in this milestone https://github.com/poliastro/poliastro/milestone/14?closed=1 (note that there might be issues without milestone!)
  - Pull requests merged since last branching https://github.com/poliastro/poliastro/pulls?q=is%3Apr+is%3Amerged+merged%3A%3E%3D2019-02-09+sort%3Aupdated-asc
* [x] Add 0.13.x branch to CI scripts

## Before the beta release

* [x] New branch
* [x] Bump version **to 0.13b1** in:
  - `README.rst`
  - `__init__.py`
  - Sphinx `conf.py`
  - AppVeyor CI script
* [x] Check that the release branch will be tested on CI
* [x] Check all the badges in `README` point to the appropriate git **branch** (replace `master` by new branch `sed -i 's/master/.../g' README.rst`)
* [x] Check that docs badges and URLs point to appropriate **tag** (replace `latest` by new tag, without sed!)
* [x] Commit
* [x] Generate sdist and bdist_wheel
* [x] `twine upload dist/* --repository-url https://test.pypi.org/legacy/`
* [x] Tag
* [x] Bump master to next development version

## Beta release

* [x] Push branch to GitHub **and tags**
* [x] Check on Test PyPI that the badges will work
* [x] Upload sdist and bdist_wheel to PyPI - *this step cannot be undone if the release is removed!* `twine upload dist/* --repository-url https://upload.pypi.org/legacy/`
* [x] Check Read the Docs (check https://docs.readthedocs.io/en/latest/webhooks.html#github first)

## Before final release

* [x] Backport any bugs
* [x] Bump version **to 0.13.0** in:
  - `README.rst`
  - `__init__.py`
  - Sphinx `conf.py`
  - AppVeyor CI script
* [x] Check that docs badges and URLs point to appropriate **tag** (replace `v0.13b1` by `v0.13.0`)
* [x] Commit
* [x] Generate sdist and bdist_wheel
* [x] `twine upload dist/* --repository-url https://test.pypi.org/legacy/`
* [x] Tag
* [x] Cherry pick the changelog with the release date

## Final release

* [x] Push tag to GitHub
* [x] Upload sdist and bdist_wheel to PyPI - *this step cannot be undone if the release is removed!* `twine upload dist/* --repository-url https://upload.pypi.org/legacy/`
* [x] Check Read the Docs (check https://docs.readthedocs.io/en/latest/webhooks.html#github first)
* [x] Create GitHub release
* [x] Add Zenodo badge to GitHub release
* [x] Send announcement email
* [x] Close milestone

**Comment by Juanlu001** [comment]
I had to manually remove the rtd_sphinx_theme fork URL from the wheel metadata, see https://github.com/pypa/pip/issues/6301

**Comment by Juanlu001** [comment]
All set! Closing :rocket:

**Comment by aqreed** [comment]
> I had to manually remove the rtd_sphinx_theme fork URL from the wheel metadata, see [pypa/pip#6301](https://github.com/pypa/pip/issues/6301)

How did you solve this? I mean, in the end, did you add the URL to install the dependency using _git+https_ in _setup.py_ anywhere?

**Comment by Juanlu001** [comment]
The URL using PEP 508 external requirements is here:

https://github.com/poliastro/poliastro/blob/0.13.x/setup.cfg#L78

So what I did was, after `python setup.py sdist bdist_wheel`, I opened the `.whl` file (which is in fact a zip or a tgz) and manually changed the `METADATA` file, which originally contains this:

```
Requires-Dist: sphinx-rtd-theme @ https://github.com/Juanlu001/sphinx_rtd_theme/archive/avoid-require-redefinition.zip ; extra == 'dev'
```
