### ISSUE TITLE
Release 0.13.1 checklist

### ISSUE THREAD

**Issue by Juanlu001** [poliastro/poliastro#795]
## Preparing the release

* [ ] ~Rerun all notebooks (pay special attention to new features)~
* [ ] ~Review documentation, optionally improving the user guide or adding new notebooks showcasing new functionality~
* [x] Write the changelog and list of contributors
  - Commits since last release branch https://github.com/poliastro/poliastro/compare/0.13.0...master
  - Issues closed in this milestone https://github.com/poliastro/poliastro/issues?q=is%3Aissue+is%3Aclosed+closed%3A%3E%3D2019-07-21+sort%3Aupdated-asc
  - Pull requests merged since last branching https://github.com/poliastro/poliastro/pulls?q=is%3Apr+is%3Amerged+merged%3A%3E%3D2019-07-21+sort%3Aupdated-asc
* [x] Add 0.13.x branch to CI scripts

## Before the beta release

* [x] New branch
* [x] Bump version **to 0.13.1b1** in:
  - `README.rst`
  - `__init__.py`
  - Sphinx `conf.py`
  - AppVeyor CI script
* [x] Check that the release branch will be tested on CI
* [x] Check all the badges in `README` point to the appropriate git **branch** (replace `master` by new branch `sed -i 's/master/.../g' README.rst`)
* [x] Check that docs badges and URLs point to appropriate **tag** (replace `latest` by new tag, without sed!)
* [x] Commit
* [x] Generate sdist and bdist_wheel
* [x] `twine upload dist/* --repository-url https://test.pypi.org/legacy/`
* [x] Tag
* [x] Bump master to next development version

## Beta release

* [x] Push branch to GitHub **and tags**
* [x] Check on Test PyPI that the badges will work
* [x] Upload sdist and bdist_wheel to PyPI - *this step cannot be undone if the release is removed!* `twine upload dist/* --repository-url https://upload.pypi.org/legacy/`
* [x] Check Read the Docs (check https://docs.readthedocs.io/en/latest/webhooks.html#github first)

## Before final release

* [x] Backport any bugs
* [x] Update release date in changelog
* [x] Bump version **to 0.13.1** in:
  - `README.rst`
  - `__init__.py`
  - Sphinx `conf.py`
  - AppVeyor CI script
* [x] Check that docs badges and URLs point to appropriate **tag** (replace `v0.13.1b1` by `v0.13.1`)
* [x] Commit
* [x] Generate sdist and bdist_wheel
* [x] `twine upload dist/* --repository-url https://test.pypi.org/legacy/`
* [x] Tag

## Final release

* [x] Push tag to GitHub
* [x] Upload sdist and bdist_wheel to PyPI - *this step cannot be undone if the release is removed!* `twine upload dist/* --repository-url https://upload.pypi.org/legacy/`
* [x] Check Read the Docs (check https://docs.readthedocs.io/en/latest/webhooks.html#github first)
* [x] Create GitHub release
* [x] Add Zenodo badge to GitHub release
* [x] Send announcement email
* [x] Cherry pick release date to master
* [x] Close milestone

**Comment by Juanlu001** [comment]
@Sedictious @jorgepiloto @shreyasbapat What issues do you think we should backport?

For example:

* https://github.com/poliastro/poliastro/pull/783 (see https://github.com/poliastro/poliastro/issues/784)
* https://github.com/poliastro/poliastro/pull/778 (in case it's still needed, not entirely sure about it)
* https://github.com/poliastro/poliastro/pull/758 (I need to check whether this landed on `master` or not)

@olebole anything that you're patching for 0.13.0 on Debian that you'd like to see fixed in 0.13.1?

**Comment by olebole** [comment]
My current patches seem to be merged: #758, #761, #767.

**Comment by Juanlu001** [comment]
> My current patches seem to be merged: #758, #761, #767.

They are in `master` though, and we will make a release in the `0.13.x` branch, so I will backport them.

**Comment by shreyasbapat** [comment]
A minor one, but might improve readability : #781 

I will look at the merged PRs and try to see if I can find something useful

**Comment by Juanlu001** [comment]
@noc0lour unfortunately I won't be able to backport #804 and #810 because we refactored all the frames code in the middle. Finishing the backports.

**Comment by noc0lour** [comment]
Alright, isn't really critical for me. Thanks for checking

**Comment by Juanlu001** [comment]
I will have to manually tweak again the release before upload because https://github.com/pypa/warehouse/issues/7136 and https://github.com/readthedocs/sphinx_rtd_theme/issues/788 are both still open.

**Comment by Juanlu001** [comment]
poliastro 0.13.1 is available! :tada: Merry Christmas :christmas_tree::santa:

**Comment by olebole** [comment]
Congratulations! I just uploaded to to Debian unstable...

**Comment by Juanlu001** [comment]
Thanks @olebole!
