### ISSUE TITLE
Release 0.14.0 checklist

### ISSUE THREAD

**Issue by astrojuanlu** [poliastro/poliastro#931]
## Preparing the release

* [x] Finish `Ephem` objects `repr` and related documentation #930
* [x] Rerun all notebooks (pay special attention to new features)
* [x] Review documentation, optionally improving the user guide or adding new notebooks showcasing new functionality
* [x] Write the changelog and list of contributors
  - Commits since last release branch https://github.com/poliastro/poliastro/compare/0.13.x...master
  - Issues closed in this milestone https://github.com/poliastro/poliastro/milestone/15?closed=1 (note that there might be issues without milestone!)
  - Pull requests merged since last branching https://github.com/poliastro/poliastro/pulls?q=is%3Apr+is%3Amerged+merged%3A%3E%3D2019-12-20+sort%3Aupdated-asc
* [x] Add 0.14.x branch to CI scripts

## Before the beta release

* [x] New branch
* [x] Bump version **to 0.14b1** in:
  - `README.rst`
  - `__init__.py`
  - Sphinx `conf.py`
  - AppVeyor CI script [TODO: Remove this from template]
* [x] Check that the release branch will be tested on CI
* [x] Check all the badges in `README` point to the appropriate git **branch** (replace `master` by new branch `sed -i 's/master/.../g' README.rst`)
* [x] Check that docs badges and URLs point to appropriate **tag** (replace `latest` by new tag, without sed!)
* [x] Commit
* [x] Generate sdist and bdist_wheel
* [x] `twine upload dist/* --repository-url https://test.pypi.org/legacy/` [TODO: Was there something about "testing" releases?]
* [x] Tag
* [x] Bump master to next development version

## Beta release

* [x] Push branch to GitHub **and tags**
* [x] Check on Test PyPI that the badges will work
* [x] Upload sdist and bdist_wheel to PyPI - *this step cannot be undone if the release is removed!* `twine upload dist/* --repository-url https://upload.pypi.org/legacy/`
* [x] Check Read the Docs (check https://docs.readthedocs.io/en/latest/webhooks.html#github first)

## Before final release

* [x] Backport any bugs
* [x] Update release date in changelog
* [x] Bump version **to 0.14.0** in:
  - `README.rst`
  - `__init__.py`
  - Sphinx `conf.py`
  - AppVeyor CI script
* [x] Check that docs badges and URLs point to appropriate **tag** (replace `v0.14b1` by `v0.14.0`)
* [x] Commit
* [x] Generate sdist and bdist_wheel
* [x] `twine upload dist/* --repository-url https://test.pypi.org/legacy/`
* [x] Tag

## Final release

* [x] Push tag to GitHub
* [x] Upload sdist and bdist_wheel to PyPI - *this step cannot be undone if the release is removed!* `twine upload dist/* --repository-url https://upload.pypi.org/legacy/`
* [x] Check Read the Docs (check https://docs.readthedocs.io/en/latest/webhooks.html#github first)
* [x] Create GitHub release
* [x] Add Zenodo badge to GitHub release
* [x] Send announcement email
* [x] Cherry pick release date to master
* [ ] Close milestone

**Comment by astrojuanlu** [comment]
poliastro 0.14b1 released :tada:

**Comment by astrojuanlu** [comment]
Backports:

* https://github.com/poliastro/poliastro/pull/954

**Comment by astrojuanlu** [comment]
poliastro 0.14.0 is available :rocket: sending announcement soon

**Comment by astrojuanlu** [comment]
Announcements done, milestone closed. See you in the next release :wave:
